version: '2'

services:
  mongo:
    restart: always
    image: "mongo:3.6.3"
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
#  mongo-express:
#    restart: always
#    image: "mongo-express:0.40.0"
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mongo
  es:
    build: es/.
    restart: always
    env_file: es/.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
#  es-head:
#    image: "mobz/elasticsearch-head:5"
#    restart: always
#    ports:
#      - "9100:9100"
#    depends_on:
#      - es